# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SCAN_V10_UI.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QTextEdit,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(500, 410)
        MainWindow.setMinimumSize(QSize(500, 410))
        MainWindow.setMaximumSize(QSize(500, 410))
        MainWindow.setStyleSheet(u".QLineEdit:focus{\n"
"border: 2px solid;\n"
"}\n"
"\n"
"QStatusBar{\n"
"background-color:rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"border: 2px solid;\n"
"}")
        self.actionopen_1 = QAction(MainWindow)
        self.actionopen_1.setObjectName(u"actionopen_1")
        self.actionopen_3 = QAction(MainWindow)
        self.actionopen_3.setObjectName(u"actionopen_3")
        self.actionopen_4 = QAction(MainWindow)
        self.actionopen_4.setObjectName(u"actionopen_4")
        self.actionopen_2 = QAction(MainWindow)
        self.actionopen_2.setObjectName(u"actionopen_2")
        self.actionopen_5 = QAction(MainWindow)
        self.actionopen_5.setObjectName(u"actionopen_5")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(280, 100, 121, 31))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.com_input1 = QLineEdit(self.centralwidget)
        self.com_input1.setObjectName(u"com_input1")
        self.com_input1.setGeometry(QRect(80, 50, 171, 31))
        font1 = QFont()
        font1.setFamilies([u"Siemens Sans Black"])
        font1.setPointSize(11)
        self.com_input1.setFont(font1)
        self.com_input1.setStyleSheet(u"")
        self.com_input2 = QLineEdit(self.centralwidget)
        self.com_input2.setObjectName(u"com_input2")
        self.com_input2.setGeometry(QRect(80, 100, 171, 31))
        self.com_input2.setFont(font1)
        self.checkBox_2 = QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(260, 100, 16, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(360, 250, 71, 31))
        self.checkBox_1 = QCheckBox(self.centralwidget)
        self.checkBox_1.setObjectName(u"checkBox_1")
        self.checkBox_1.setGeometry(QRect(260, 50, 21, 31))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(140, 260, 61, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 260, 61, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(220, 250, 51, 31))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(200, 320, 91, 31))
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(280, 260, 71, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.voltage_edit = QLineEdit(self.centralwidget)
        self.voltage_edit.setObjectName(u"voltage_edit")
        self.voltage_edit.setGeometry(QRect(40, 280, 71, 31))
        font2 = QFont()
        font2.setFamilies([u"Siemens Sans"])
        font2.setPointSize(11)
        self.voltage_edit.setFont(font2)
        self.voltage_edit.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 10, 201, 20))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.label.setFont(font3)
        self.pushButton_1 = QPushButton(self.centralwidget)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(280, 50, 121, 31))
        self.pushButton_1.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 250, 51, 31))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(110, 280, 61, 31))
        self.com_edit = QLineEdit(self.centralwidget)
        self.com_edit.setObjectName(u"com_edit")
        self.com_edit.setGeometry(QRect(200, 280, 91, 31))
        self.com_edit.setFont(font2)
        self.com_edit.setAlignment(Qt.AlignCenter)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(410, 260, 61, 20))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.current_monitor = QLineEdit(self.centralwidget)
        self.current_monitor.setObjectName(u"current_monitor")
        self.current_monitor.setEnabled(False)
        self.current_monitor.setGeometry(QRect(340, 280, 91, 31))
        self.current_monitor.setFont(font2)
        self.current_monitor.setStyleSheet(u"QLineEdit{\n"
"background-color: green;\n"
"color: rgb(255,255,255);\n"
"}\n"
"")
        self.current_monitor.setAlignment(Qt.AlignCenter)
        self.current_monitor.setReadOnly(False)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 350, 461, 20))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(0, 270, 21, 91))
        self.line_6.setFrameShadow(QFrame.Raised)
        self.line_6.setMidLineWidth(0)
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(460, 270, 20, 91))
        self.line_7.setFrameShadow(QFrame.Raised)
        self.line_7.setFrameShape(QFrame.VLine)
        self.textEdit_1 = QTextEdit(self.centralwidget)
        self.textEdit_1.setObjectName(u"textEdit_1")
        self.textEdit_1.setEnabled(True)
        self.textEdit_1.setGeometry(QRect(20, 160, 211, 91))
        font4 = QFont()
        font4.setFamilies([u"Siemens Sans"])
        font4.setPointSize(10)
        self.textEdit_1.setFont(font4)
        self.textEdit_1.setUndoRedoEnabled(True)
        self.textEdit_2 = QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setGeometry(QRect(250, 160, 211, 91))
        self.textEdit_2.setFont(font4)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(0, 150, 21, 121))
        self.line_8.setFrameShadow(QFrame.Raised)
        self.line_8.setMidLineWidth(0)
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(460, 150, 20, 121))
        self.line_9.setFrameShadow(QFrame.Raised)
        self.line_9.setFrameShape(QFrame.VLine)
        self.line_10 = QFrame(self.centralwidget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(10, 140, 81, 16))
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.centralwidget)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(390, 140, 81, 20))
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line_12 = QFrame(self.centralwidget)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(150, 140, 181, 20))
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 130, 51, 31))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(340, 130, 51, 31))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(110, 320, 61, 31))
        self.indicator_1 = QLabel(self.centralwidget)
        self.indicator_1.setObjectName(u"indicator_1")
        self.indicator_1.setGeometry(QRect(410, 50, 61, 31))
        self.indicator_2 = QLabel(self.centralwidget)
        self.indicator_2.setObjectName(u"indicator_2")
        self.indicator_2.setGeometry(QRect(410, 100, 61, 31))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(340, 320, 91, 31))
        self.pushButton.setStyleSheet(u"QPushButton{\n"
"background-color:red;\n"
"color:white;\n"
"}\n"
"")
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(360, 10, 91, 20))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(370, 360, 71, 20))
        self.label_workstation = QLabel(self.centralwidget)
        self.label_workstation.setObjectName(u"label_workstation")
        self.label_workstation.setGeometry(QRect(440, 360, 41, 20))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(40, 320, 71, 31))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(439, 280, 21, 31))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 71, 31))
        font5 = QFont()
        font5.setFamilies([u"Siemens Sans Black"])
        font5.setPointSize(11)
        font5.setBold(False)
        self.label_9.setFont(font5)
        self.label_9.setStyleSheet(u"QLabel{\n"
"border:0.5px solid rgb(0,0,0);\n"
"}")
        self.label_9.setMargin(0)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 100, 71, 31))
        self.label_10.setFont(font5)
        self.label_10.setStyleSheet(u"QLabel{\n"
"border:0.5px solid rgb(0,0,0);\n"
"}")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 500, 22))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_5 = QMenu(self.menubar)
        self.menu_5.setObjectName(u"menu_5")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_6 = QMenu(self.menubar)
        self.menu_6.setObjectName(u"menu_6")
        self.menu_8 = QMenu(self.menubar)
        self.menu_8.setObjectName(u"menu_8")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menu_2.addAction(self.actionopen_1)
        self.menu_5.addAction(self.actionopen_3)
        self.menu_3.addAction(self.actionopen_4)
        self.menu_6.addAction(self.actionopen_2)
        self.menu_8.addAction(self.actionopen_5)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"scan_v10", None))
        self.actionopen_1.setText(QCoreApplication.translate("MainWindow", u"open", None))
#if QT_CONFIG(shortcut)
        self.actionopen_1.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+1", None))
#endif // QT_CONFIG(shortcut)
        self.actionopen_3.setText(QCoreApplication.translate("MainWindow", u"open", None))
#if QT_CONFIG(shortcut)
        self.actionopen_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.actionopen_4.setText(QCoreApplication.translate("MainWindow", u"open", None))
#if QT_CONFIG(shortcut)
        self.actionopen_4.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+4", None))
#endif // QT_CONFIG(shortcut)
        self.actionopen_2.setText(QCoreApplication.translate("MainWindow", u"open", None))
#if QT_CONFIG(shortcut)
        self.actionopen_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionopen_5.setText(QCoreApplication.translate("MainWindow", u"open", None))
#if QT_CONFIG(shortcut)
        self.actionopen_5.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+5", None))
#endif // QT_CONFIG(shortcut)
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.checkBox_2.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u7535\u6d41", None))
        self.checkBox_1.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6e90\u8fde\u63a5", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u4e32\u53e3", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Please Scan the CP number!", None))
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u7535\u538b", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u7535\u538b", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"INFO 1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"INFO 2", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u7535\u538b\u56de\u96f6", None))
        self.indicator_1.setText(QCoreApplication.translate("MainWindow", u"Waitting...", None))
        self.indicator_2.setText(QCoreApplication.translate("MainWindow", u"Waitting...", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u675f\u5e76\u91cd\u542f", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Auto Booting", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u5de5\u4f5c\u7ad9\uff1a", None))
        self.label_workstation.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"110", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"48", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"24", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"0", None))

        self.label_8.setText(QCoreApplication.translate("MainWindow", u"mA", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"COM1/3", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"COM2/4", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"SCAN V10", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u754c\u9762", None))
        self.menu_5.setTitle(QCoreApplication.translate("MainWindow", u"\u65e5\u5fd7\u6587\u4ef6", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u7248\u672c\u6587\u4ef6(10.1)", None))
        self.menu_6.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.menu_8.setTitle(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
    # retranslateUi

